version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - myapp-network

  backend:
    image: jessica1295/online-learning-backend
    container_name: backend
    networks:
      - myapp-network
    depends_on:
      - mongo

  frontend:
    image: jessica1295/online-learning-frontend
    ports:
      - 3000:3000
    networks:
      - myapp-network
    depends_on:
      - backend
networks:
  myapp-network:
    driver: bridge
